version: '3.8'
services:
  php-apache-environment:
    image: helhas/kuis2
    container_name: php-apache
    depends_on:
      - db
    volumes:
      - ./php/src:/var/www/html/
    ports:
      - 8000:80
    networks:
      - backend

  db:
    container_name: db
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Admin123.
      MYSQL_DATABASE: oop_pdo_crud
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql
      - ./oop_pdo_crud.sql:/docker-entrypoint-initdb.d/oop_pdo_crud.sql
    networks:
      - backend

volumes:
  db:

networks:
  backend:
    name: backend-network
    ipam:
      driver: default
      config:
        - subnet: 10.0.0.0/24